config/routes.rb
WorkFu::Application.routes.draw do
  devise_for :users, :path => "usuarios", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
  devise_scope :user do
  get "sign_in", :to => "devise/sessions#new"
  match "/logout" => "devise/sessions#destroy"  
  resources :keywords
end

  
  resources :navigatebars  
  root :to=> "pages#index"
  
  
  
  resources :user do
    resources :keywords
  end
  
  match "ajax", :to=>'pages#ajax'
  match "movie_new", :to=>'pages#movie_new', :via  => "post"
  match "ajax_movie_new", :to=>'pages#ajax_movie_new', :via  => "post"

  match "/refine_your_keywords", :to=>'navigatebars#refine_your_keywords'
  match "/add_other_networks", :to=>'navigatebars#add_other_networks'
  match "/reading_list", :to=>'navigatebars#reading_list'
  match "/preview_your_profille", :to=>'navigatebars#preview_your_profille'
  match "/your_profile", :to => 'navigatebars#update_your_bio'
  
  match "index", :to=> 'pages#index'
  match "/create_manage", :to=>'pages#create_manage'  
  match "/messages", :to=>'pages#messages'
  match "/settings", :to=>'pages#settings'
  match "/your_applications", :to=>'pages#your_applications'
  match "/opportunities", :to=>'pages#opportunities'  

  

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
   attr_accessible :keyword
  belongs_to :user
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :title 
end

app/models/network.rb
class Network < ActiveRecord::Base
  attr_accessible :title
end

app/models/register.rb
class Register < ActiveRecord::Base
  attr_accessible :First_name, :Last_Name, :email, :location, :microBio, :personal_url, :profesionalBio, :userName
end

app/models/test.rb
class Test < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :username, :personal_url, :location, :micro_bio, :profesional_bio, :group_individual, :usetype_ids, :avatar
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :micro_bio, :length   => { :maximum => 160 }  
  validates :email, :format   => { :with => email_regex }
  validates :profesional_bio, :length => {:within => 0..1000}
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_many :keywords
  has_many :tests

  has_many :usetype_users
  has_many :usetypes, :through => :usetype_users

end

app/models/usetype.rb
class Usetype < ActiveRecord::Base
  attr_accessible :title

  has_many :usetype_users, :dependent => :destroy
  has_many :users, :through =>  :usetype_users
end

app/models/usetype_user.rb
class UsetypeUser < ActiveRecord::Base
  attr_accessible :user_id, :usetype_id

  belongs_to :user
  belongs_to :usetype
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
	def index
	    
		
	end
	
	def create		
		@user = User.find(params[:user_id])			
		@user.keywords.create(params[:keyword])
		@user.save

		redirect_to :controller => "navigatebars", :action => "refine_your_keywords"
	end

	def destroy
		puts "xxxxx xxxx xxxxx"
		puts "destroy"
		@keyword = Keyword.find(params[:id])
		@keyword.destroy

		redirect_to :controller => "navigatebars", :action => "refine_your_keywords"
	end

	#def show
	#	puts "xxxxx xxxx xxxxx"
	#	puts "destroy"
	#	redirect_to :controller => "navigatebars", :action => "refine_your_keywords"
	#end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authenticate_user!
  def index
    @user = User.first
    a = @user.keywords.first
    #@k = @user.keywords.build
    #@k.keyword = "kkk"
    #@k.save

  end  

  def register_form
    @title = "Registration"
  end
  def create_manage
    session[:right_tab] = 5
    @title = "Create/Manage"
  end
  def messages
     session[:right_tab] = 2
    @title = "Messages"
  end
  def settings
    session[:right_tab] = 3
    @title = "Settings"
  end
  def your_applications
    session[:right_tab] = 4
    @title = "Your Applications"
  end
  def opportunities
    session[:right_tab] = 6
    @title = "Opportunities"
  end


  def home
    @title = "Home"
    session[:right_tab] = 0
  end
 
 def update
   puts params
 end 

 def ajax
 @movies = Movie.all   
 end

 def movie_new
  @movie = Movie.create(params[:movie])
   respond_to do |format|
      format.html do
        redirect_to :action => "ajax"
      end  
     
      format.js do 
        @movies = Movie.all  
      end 
    end 

 end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  

  def register_form
    @title = "Registration"
  end
  def create_manage
    @title = "Create/Manage"
  end
  def messages
    @title = "Messages"
  end
  def settings
    @title = "Settings"
  end
  def your_applications
    @title = "Your_Applications"
  end
  def your_profille
    @title = "Your Profille"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/navigatebar_helper.rb
module NavigatebarHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
         <div class="container">            
              <ul>  
                <li>Follow us on <a href="http://twitter.com/">Twitter</a> & Like us on <a href="http://facebook.com/">Facebook</a>. </li>
              </ul>       
              <ul orientation="horizontal" >      
                 <li><%= link_to "Information", '#' %>.</li>       
                 <li><%= link_to "FAQ's", '#' %>.</li>
                 <li><%= link_to "Blog", '#' %>.</li>
                 <li><%= link_to "Terms", '#' %>.</li>
                 <li><%= link_to "Privacy", :controller => "home#index" %>.</li>                 
              </ul>   
                
         </footer>  

app/views/layouts/_header.html.erb
<header>
		<nav class="round">
          <ul>                        
            <li><%= link_to "Create/Manage", update_your_bio_path %></li>
            <li><%= link_to "Refine your Keywords", '#' %></li>
            <li><%= link_to "Add other networks", '#' %></li>
            <li><%= link_to "Reading List", '#' %></li>            
            <li><%= link_to "Preview yoyr Profile", '#' %></li>
          </ul>
        </nav>
	</header>

app/views/layouts/_header2.html.erb
<header>
		<nav2 class="round">
          <ul>                        
            <li><%= link_to "Update your Bio", update_your_bio_path %></li>
            <li><%= link_to "Refine your Keywords", '#' %></li>
            <li><%= link_to "Add other networks", '#' %></li>
            <li><%= link_to "Reading List", '#' %></li>            
            <li><%= link_to "Preview yoyr Profile", '#' %></li>
          </ul>
        </nav>
	</header>

app/views/layouts/_navigate.html.erb
<header> 
       <div class="navbar">
           <div class="navbar-inner">
               <div class="container">
               
                   <ul class="nav nav-pills pull-left">                                   
                       <li><a href="/index", title="Workfu", alt="Workfu"><%= image_tag("workfu_logo.png", :alt => "WorkFu", :class => "round") %></a></li>  
                       <% if session[:right_tab] == 6 %>    
                          <li class="active"><%= link_to "Opportunities", opportunities_path %></li>
                       <%else%>            
                          <li ><%= link_to "Opportunities", opportunities_path %></li>
                       <%end%>   
                       <% if session[:right_tab] == 5 %>    
                          <li class="active"><%= link_to "Create/Manage", create_manage_path %></li>
                       <%else%>   
                          <li ><%= link_to "Create/Manage", create_manage_path %></li>
                       <%end%>
                       <% if session[:right_tab] == 4 %>       
                          <li class="active"><%= link_to "Your Applications", your_applications_path %></li>
                       <%else%>                       
                          <li ><%= link_to "Your Applications", your_applications_path %></li>
                       <%end%>
                   </ul>
                       
                   <ul class="nav nav-pills pull-right">
                       <% if session[:right_tab] == 1 %>                      
                          <li class="active"><%= link_to "Your Profile", your_profile_path %></li> 
                       <%else%>
                          <li><%= link_to "Your Profile", your_profile_path %></li> 
                       <%end%> 
                        <% if session[:right_tab] == 2 %>
                          <li class="active"><%= link_to "Messages", messages_path %></li> 
                        <%else%>
                           <li ><%= link_to "Messages", messages_path %></li>     
                        <%end%>
                        <% if session[:right_tab] == 3 %>      
                           <li class="active"><%= link_to "Settings", settings_path %></li>
                        <%else%>
                           <li ><%= link_to "Settings", settings_path %></li>
                        <%end%>
                           <li ><%= link_to "Logout", logout_path%></li>
                   </ul>
               </div>
           </div>              
       </div>   
       </header>

app/views/layouts/_navigation_index.html.erb
<header> 
       <div class="navbar">
           <div class="navbar-inner">
               <div class="container">
               
                   <ul class="nav nav-pills pull-left">                                   
                       <li><a href="http://twitter.com/", title="twitter", alt="twitter"><%= image_tag("twitter_logo_right.png", :alt => "twitter", :class => "round") %></a></li>      
                   </ul>
                       
                   <ul class="nav nav-pills pull-right">                              
                   
                          <li ><%= link_to "Sign up", new_user_registration_path %></li>  
                          <li ><%= link_to "Sign in", new_user_session_path %></li>  
                   
                   </ul>
               </div>
           </div>              
       </div>   
  </header>

app/views/layouts/_stylesheets.html.erb
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/_stylesheets2.html.erb
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
    <%= stylesheet_link_tag 'custom2', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=@title%></title>
         
         <%= stylesheet_link_tag 'application', :media => 'all' %>
         <%= javascript_include_tag 'application' %>   
         <%= csrf_meta_tags %>  
</head>
<body >
<% if user_signed_in?%>	
	     <%= render 'layouts/navigate'%>       
<%else%>
  <%= render 'layouts/navigation_index'%>
  <%end%>
       <section>
         <div class="container">
            <%= yield %>
         <div/>
       </section>
       <%= render 'layouts/footer'%>
       </div>
</body>
</html>

app/views/layouts/profilles.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=@title%></title>
         <%= csrf_meta_tags %>
         <%= stylesheet_link_tag 'application', :media => 'all' %>
         <%= javascript_include_tag 'application' %>     
</head>
<body>
	<header>
       
	     <div class="container">
             <ul class="nav nav-pills"> 
                 <% if session[:second_tab] == 1 %>                       
                      <li class="active"><%= link_to "Update your Bio", your_profile_path %></li>
                 <%else%>
                     <li><%= link_to "Update your Bio", your_profile_path %></li>     
                 <%end%>
                 <% if session[:second_tab] == 2 %>                       
                     <li class="active"><%= link_to "Refine your Keywords", refine_your_keywords_path %></li>
                 <%else%>
                     <li><%= link_to "Refine your Keywords", refine_your_keywords_path %></li>
                 <%end%>
                 <% if session[:second_tab] == 3 %>                       
                     <li class="active"><%= link_to "Add other networks", add_other_networks_path %></li>
                 <%else%>
                     <li><%= link_to "Add other networks", add_other_networks_path %></li>
                 <%end%>
                 <% if session[:second_tab] == 4 %>                       
                     <li class="active"><%= link_to "Reading List", reading_list_path %></li>
                 <%else%>            
                     <li><%= link_to "Reading List", reading_list_path %></li>
                <%end%>
                 <% if session[:second_tab] == 5 %>                       
                     <li class="active"><%= link_to "Preview your Profille", preview_your_profille_path %></li>
                 <%else%>
                     <li><%= link_to "Preview your Profille", preview_your_profille_path %></li>
                <%end%>
             </ul>
             <section >
                <% flash.each do |key, value| %>
                <div class="alert alert-<%= key %>"><%= value %></div>
                <% end %>
                <%= yield %>
      </section>
         </div>         
   </header>
</body>

app/views/pages/_movie.html.erb
<table>
	<tr>
		<td>Title</td>
	</tr>
	<%@movies.each do |t|%>
	<tr>
		<td><%=t.title%></td>
	</tr>
<%end%>
</table>

app/views/pages/ajax.html.erb
<h1>Hello world!!!</h1>
<div id="movies">
 <%= render 'movie'%>
</div> 
<%=form_for Movie.new, :url => {:controller=>"pages", :action => "movie_new" }, :remote => true  do |f| %>
<%= f.text_field :title %>
<%= f.submit "Create" %>
<%end%>

		

app/views/pages/create_manage.html.erb
<h3 align="center">We're now accepting requests to post opportunities</h3>

<a href="#" class="btn btn-primary btn-large" align="center">Request Access Now</a>
<p align="center">During the beta phase, posting opportunities on WorkFu will be completely free. Once the beta phase closes, paid plans will come into effect. You will not pay a penny until you choose a plan type & there will always be a free plan.</p>

app/views/pages/index.html.erb
<div class="row-fluid" align="left">
	<div class="span12" >
Level 1 of column
    <div class="row-fluid">
       <div class="span6">
       	<h1>It's good to see you <%=current_user.first_name%></h1>
       	<p>We're launching the full beta on the 21st of May. In the meantime please update & prepare your 'Smart Profile'.</p>
       </div>
           <div class="span6">
            <p style:"fomt-size:20px"><%=current_user.first_name%> <%=current_user.last_name%></p>
            <%= image_tag current_user.avatar.url, :size => "128x128" %>            
                       
          </div>
           <%=link_to "go to AJAX", ajax_path%>
    </div>
    </div>
</div>

app/views/pages/movie_new.js.erb
$("#movies").html("<%= escape_javascript(render 'movie') %>");

app/views/pages/opportunities.html.erb
<h1 align="center">Coming very soon!</h1>
<p align="center">We're not quite ready to show you this section.</p>
<p align="center">We are officially launching the full beta on the 21st of May, but we are going to start rolling out updates to users already in the system a little earlier.</p>
<p align="center">In the meantime, you can follow us for announcements.</p>
<p align="center">If you want to be one of the first to see the launch version of WorkFu, please tweet us!</p>
<p align="center">If you have opportunities you wish to post, you can request access or if you already have access you can get started here.</p>

app/views/pages/register_form.html.erb
<title>
	<%=@title=%>
   <%= stylesheet_link_tag 'home', :media => 'screen' %>
</title>
<body>
   <div>
      <div class="description">
            <h1>Edit your profile</h1>
            <p>Use the form below to edit and manage your personal details.</p>
      </div>
   </div>
   <section role="main">
<%= form_tag(:multipart=>true) do %>
         <div >
               <%=label_tag(:first_name, "First name") =%></br>
              <%= text_field_tag(:first_name) %> 
         </div>   
   <div class="right lastname">      
      <%=label_tag(:last_name, "Last name") =%></br>
      <%= text_field_tag(:last_name) %>
   </div>   
   <div class="email">
      <%=label_tag(:email, "E-mail") =%></br>
      <%= text_field_tag(:email) %>
   </div>   
   <div class="right">
      <%=label_tag(:user_name, "Username/WorkFu URL") =%></br>
      <%= text_field_tag(:user_name) %>
   </div>
   
   <div>
      <%=label_tag(:personal_url, "Personal URL") =%></br>
      <%= text_field_tag(:personal_url) %>
   </div>
   
   <div class="right">
      <%=label_tag(:location, "Location") =%></br>
      <%= text_field_tag(:location) %>
   </div>
   
   <div class="microbiography">
      
      <%=label_tag(:micro_bio, "Micro Bio") =%><span>(Achievements / Current position)</span></br>
      <%= text_area_tag(:micro_bio) %>
      <!--<span class="character-count">
         Used
         <span class="count">0</span>
         /
         <span class="total">160</span>
         characters. No HTML allowed.
      </span>-->
   </div>
   
   <div class="biography">
      
      <%=label_tag(:proffessional_bio, "Proffessional Bio") =%></br>
      <%= text_area_tag "proffessional_bio", nil %>
      <!--<span class="character-count">
         Used
         <span class="count">3</span>
         /
         <span class="total">200</span>
         words. We allow
         <a title="View details" target="_blank" href="http://daringfireball.net/projects/markdown/syntax">Markdown</a>
         <span class="mdprev"> (edit for preview)</span>.
      </span>-->
   </div>
   
   <%= submit_tag("Update") %>
   <% end %>
</section>
</body>

app/views/pages/update_your_bio.html.erb
<h1>Hello world dfdfb</h1>

app/views/pages/your_applications.html.erb
<h1 align="center">Coming very soon!</h1>
<p align="center">We're not quite ready to show you this section.</p>
<p align="center">We are officially launching the full beta on the 21st of May, but we are going to start rolling out updates to users already in the system a little earlier.</p>
<p align="center">In the meantime, you can follow us for announcements.</p>
<p align="center">If you want to be one of the first to see the launch version of WorkFu, please tweet us!</p>
<p align="center">If you have opportunities you wish to post, you can request access or if you already have access you can get started here.</p>

app/views/pages/your_profille.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=@title%></title>
  <%= csrf_meta_tags %>
         <%= stylesheet_link_tag 'application', :media => 'all' %>
         <%= javascript_include_tag 'applicattion' %>      
  </head>
<body>
	<header>
	<div class="container">
		
	<div/>	
    </header>
         <section class="round">
            <%= yield %>
         </section>         
    <footer>
    	<%= yield %>
    </footer>
</body>
</html>